### PR TITLE
adding data from july 2023 to january 2024

### PR DESCRIPTION
**Pull request by jstelnik**

### CODE REVIEW

**Comment by jstelnik** [comment]
THINGS TO DO TO FINISH DATA SEEDING:

VOLUNTEER DATA:

- [ ] format names for 2024 data
- [ ] IF TIME: go through 2022-2023 data and add regularFoodTaken and damagedFoodTaken to the data.js files. Two columns (What category of food?,Weight (Numbers only!)) in VolunteerData.csv file. Currently not considered in data.js file. 

IMPORT DATA:

- [ ] format names for 2024 data
- [ ] format categories for 2024 data
- [ ] format distributors for 2024 data

EXPORT DATA:

- [ ] format names for 2024 data
- [ ] format categories for 2024 data
- [ ] format locations for 2024 data
- [ ] add new data into data.js file in exportsList

**Comment by John3927** [comment]
In volunteer.ipynb, for the export, you have

```
export_df['WEIGHT'] = export_df['WEIGHT'].astype(str).str.replace(',', '').astype(int)
export_df = export_df.drop(columns = ['DATE', 'NAME', 'WEIGHT', 'PRODUCT', 'CLIENT'])

...

# print('[')
# for i, row in export_df.iterrows():
#     print('\t{')
#     print('\t\tdate: ' + '"' + row['date'] + '"' + ',')
#     print('\t\tname: ' + '"'+ row['name'] + '"' +',')
#     print('\t\tweight: ' + row['weight'] +',')
#     print('\t\tcategory: ' + '"'+ row['category'] + '"' +',')
#     print('\t\tlocation: ' + '"'+ row['location']+ '"')
#     print('\t},')
# print(']')
```

I assume the first line is actually

```
export_df['weight'] = export_df['WEIGHT'].astype(str).str.replace(',', '').astype(int)
```

with lower case weight in the first column name?

**Comment by John3927** [comment]
Is Crystal Shaw the same person as Crystal [Kingdom Woship Center] ?

**Comment by jstelnik** [comment]
> Is Crystal Shaw the same person as Crystal [Kingdom Woship Center] ?

@John3927 I assume so. I think there's only one Crystal. But I think Crystal [Kingdom Woship Center] is a location and Crystal Shaw might be a volunteer. Most likely the same Crystal though.

**Comment by John3927** [comment]
I see creamer, yogurt, coffee... in the list. How do I know if they are Danone products or not? For example, would something listed as "coffee" get changed into "Danone - Coffe" or something else (I don't exactly know what coffee goes into... Dry drink?)

**Comment by jstelnik** [comment]
> I see creamer, yogurt, coffee, oatmilk... in the list. How do I know if they are Danone products or not? For example, would something listed as "coffee" get changed into "Danone - Coffe" or something else (I don't exactly know what coffee goes into... Dry drink?)
> 
> Also, what is the difference between Drinks [Dry] and Drinks [Fridge]? If I see something simply listed as Drinks, which one should I update it to?

@John3927 

for dannon/danone products, only list is at such if it explicitly says it in the name. for just coffee maybe just do drinks dry. creamer, yogurt can do dairy. oatmilk can be drinks fridge. just wherever you would put it in your house, to a point. 

drinks dry is like milk powder, lemonade powder, etc. things that don't need to be in the fridge. drinks fridge would be like orange juice, actual milk, etc. i would default to drinks [dry] - it is WAY more common than drinks [fridge]. 

Hope this helps!

**Comment by John3927** [comment]
Hi,

I added the new values. I can also commit the Volunteer.ipynb file that I used to edit the data if you want to verify.

**Comment by jstelnik** [comment]
Sure! Add the file. I can always remove it. Thank you!! @John3927

**Comment by jstelnik** [comment]
Hey @John3927 I'm making changes on the branch with the data so just make sure you git pull before you work next time

**Review by ChrisWilhelm — APPROVED** [review]

**Pull request merged**
